import type { ContentItem } from '@/types/tags';

// Dati di contenuto mock (placeholder). Nessun fetch reale: da sostituire con
// query Supabase. Titoli, circuiti e nazioni sono realistici ma fittizi.
export const mockContent: ContentItem[] = [
  // ----- 3 live (type: 'live', isLive: true) -----
  {
    id: 'live-1',
    title: 'FIPAV Campionato Italiano — Semifinale',
    teams: 'Lupo / Nicolai vs Ranghieri / Carambula',
    circuit: 'FIPAV',
    sport: 'Beach Volley',
    type: 'live',
    nations: ['Italia'],
    event: 'Semifinale',
    viewerCount: 12840,
    isLive: true,
    isPremium: true,
    date: '26 Jun 2026',
    tags: ['FIPAV', 'Beach Volley', 'live', 'Italia', 'Semifinale'],
  },
  {
    id: 'live-2',
    title: 'AIBVC Tour — Quarti di finale',
    teams: 'Carambula / Cottafava vs Gori / Cattaneo',
    circuit: 'AIBVC',
    sport: 'Beach Volley',
    type: 'live',
    nations: ['Italia'],
    event: 'Quarti',
    viewerCount: 8210,
    isLive: true,
    isPremium: true,
    date: '26 Jun 2026',
    tags: ['AIBVC', 'Beach Volley', 'live', 'Italia', 'Quarti'],
  },
  {
    id: 'live-3',
    title: 'AVP America — Finale',
    teams: 'Crabb / Brunner vs Partain / Benesh',
    circuit: 'AVP',
    sport: 'Beach Volley',
    type: 'live',
    nations: ['USA'],
    event: 'Finale',
    viewerCount: 15470,
    isLive: true,
    isPremium: false,
    date: '26 Jun 2026',
    tags: ['AVP', 'Beach Volley', 'live', 'USA', 'Finale'],
  },

  // ----- 6 replay (type: 'replay') -----
  {
    id: 'replay-1',
    title: 'Beach Pro Tour — Finale',
    teams: 'Mol / Sørum vs Plavins / Tocs',
    circuit: 'BPT',
    sport: 'Beach Volley',
    type: 'replay',
    nations: ['Norvegia', 'Germania'],
    event: 'Finale',
    duration: '1:42:10',
    isPremium: true,
    date: '20 Jun 2026',
    tags: ['BPT', 'Beach Volley', 'replay', 'Norvegia', 'Germania', 'Finale'],
  },
  {
    id: 'replay-2',
    title: 'Beach Pro Tour — Quarti di finale',
    teams: 'Brouwer / Meeuwsen vs Cherif / Ahmed',
    circuit: 'BPT',
    sport: 'Beach Volley',
    type: 'replay',
    nations: ['Olanda'],
    event: 'Quarti',
    duration: '1:31:18',
    isPremium: true,
    date: '19 Jun 2026',
    tags: ['BPT', 'Beach Volley', 'replay', 'Olanda', 'Quarti'],
  },
  {
    id: 'replay-3',
    title: 'FIPAV Campionato Italiano — Finale',
    teams: 'Lupo / Nicolai vs Rossi / Carambula',
    circuit: 'FIPAV',
    sport: 'Beach Volley',
    type: 'replay',
    nations: ['Italia'],
    event: 'Finale',
    duration: '2:05:48',
    isPremium: true,
    date: '15 Jun 2026',
    tags: ['FIPAV', 'Beach Volley', 'replay', 'Italia', 'Finale'],
  },
  {
    id: 'replay-4',
    title: 'CEV European Championship — Semifinale',
    teams: 'Ehlers / Wickler vs Brouwer / Meeuwsen',
    circuit: 'CEV',
    sport: 'Beach Volley',
    type: 'replay',
    nations: ['Germania', 'Olanda'],
    event: 'Semifinale',
    duration: '1:18:22',
    isPremium: false,
    date: '12 Jun 2026',
    tags: ['CEV', 'Beach Volley', 'replay', 'Germania', 'Olanda', 'Semifinale'],
  },
  {
    id: 'replay-5',
    title: 'AVP America — Finale',
    teams: 'Lucena / Dalhausser vs Gibb / Crabb',
    circuit: 'AVP',
    sport: 'Beach Volley',
    type: 'replay',
    nations: ['USA'],
    event: 'Finale',
    duration: '1:47:55',
    isPremium: true,
    date: '08 Jun 2026',
    tags: ['AVP', 'Beach Volley', 'replay', 'USA', 'Finale'],
  },
  {
    id: 'replay-6',
    title: 'AVP America — Quarti di finale',
    teams: 'Partain / Benesh vs Evans / Budinger',
    circuit: 'AVP',
    sport: 'Beach Volley',
    type: 'replay',
    nations: ['USA', 'Brasile'],
    event: 'Quarti',
    duration: '1:22:40',
    isPremium: true,
    date: '07 Jun 2026',
    tags: ['AVP', 'Beach Volley', 'replay', 'USA', 'Brasile', 'Quarti'],
  },

  // ----- 4 interviste (type: 'interview') -----
  {
    id: 'interview-1',
    title: 'Intervista esclusiva: Anders Mol',
    circuit: 'FIVB',
    sport: 'Beach Volley',
    type: 'interview',
    nations: ['Norvegia'],
    duration: '0:14:32',
    isPremium: true,
    date: '21 Jun 2026',
    tags: ['FIVB', 'Beach Volley', 'interview', 'Norvegia'],
  },
  {
    id: 'interview-2',
    title: 'Quattro chiacchiere con Paolo Nicolai',
    circuit: 'FIPAV',
    sport: 'Beach Volley',
    type: 'interview',
    nations: ['Italia'],
    duration: '0:11:08',
    isPremium: false,
    date: '16 Jun 2026',
    tags: ['FIPAV', 'Beach Volley', 'interview', 'Italia'],
  },
  {
    id: 'interview-3',
    title: 'AVP Stories: Taylor Crabb',
    circuit: 'AVP',
    sport: 'Beach Volley',
    type: 'interview',
    nations: ['USA'],
    duration: '0:18:45',
    isPremium: true,
    date: '09 Jun 2026',
    tags: ['AVP', 'Beach Volley', 'interview', 'USA'],
  },
  {
    id: 'interview-4',
    title: 'Beach Pro Tour: il dietro le quinte di Cherif Younousse',
    circuit: 'BPT',
    sport: 'Beach Volley',
    type: 'interview',
    nations: ['Francia'],
    duration: '0:09:50',
    isPremium: true,
    date: '05 Jun 2026',
    tags: ['BPT', 'Beach Volley', 'interview', 'Francia'],
  },

  // ----- 4 highlights (type: 'highlights') -----
  {
    id: 'highlights-1',
    title: 'Beach Pro Tour — Top 10 dei punti',
    circuit: 'BPT',
    sport: 'Beach Volley',
    type: 'highlights',
    nations: ['Olanda', 'Norvegia'],
    event: 'Finale',
    duration: '0:08:12',
    isPremium: true,
    date: '20 Jun 2026',
    tags: ['BPT', 'Beach Volley', 'highlights', 'Olanda', 'Norvegia', 'Finale'],
  },
  {
    id: 'highlights-2',
    title: 'FIPAV — I migliori scambi della Semifinale',
    circuit: 'FIPAV',
    sport: 'Beach Volley',
    type: 'highlights',
    nations: ['Italia'],
    event: 'Semifinale',
    duration: '0:06:40',
    isPremium: false,
    date: '15 Jun 2026',
    tags: ['FIPAV', 'Beach Volley', 'highlights', 'Italia', 'Semifinale'],
  },
  {
    id: 'highlights-3',
    title: 'AVP America — Highlights della Finale',
    circuit: 'AVP',
    sport: 'Beach Volley',
    type: 'highlights',
    nations: ['USA'],
    event: 'Finale',
    duration: '0:07:55',
    isPremium: true,
    date: '08 Jun 2026',
    tags: ['AVP', 'Beach Volley', 'highlights', 'USA', 'Finale'],
  },
  {
    id: 'highlights-4',
    title: 'King & Queen — Le giocate decisive',
    circuit: 'King & Queen',
    sport: 'Beach Volley',
    type: 'highlights',
    nations: ['Italia'],
    duration: '0:05:30',
    isPremium: true,
    date: '02 Jun 2026',
    tags: ['King & Queen', 'Beach Volley', 'highlights', 'Italia'],
  },

  // ----- 3 dietro le quinte (type: 'behind-the-scenes') -----
  {
    id: 'bts-1',
    title: 'Dietro le quinte: una giornata al Beach Pro Tour',
    circuit: 'BPT',
    sport: 'Beach Volley',
    type: 'behind-the-scenes',
    nations: ['Norvegia'],
    duration: '0:16:20',
    isPremium: true,
    date: '21 Jun 2026',
    tags: ['BPT', 'Beach Volley', 'behind-the-scenes', 'Norvegia'],
  },
  {
    id: 'bts-2',
    title: 'Marathon Tour: la notte prima della Finale',
    circuit: 'Marathon',
    sport: 'Beach Volley',
    type: 'behind-the-scenes',
    nations: ['Italia'],
    duration: '0:12:48',
    isPremium: true,
    date: '14 Jun 2026',
    tags: ['Marathon', 'Beach Volley', 'behind-the-scenes', 'Italia'],
  },
  {
    id: 'bts-3',
    title: 'Beach Tennis: dentro lo spogliatoio degli azzurri',
    circuit: 'Beach Pro Tour',
    sport: 'Beach Tennis',
    type: 'behind-the-scenes',
    nations: ['Italia'],
    duration: '0:10:05',
    isPremium: false,
    date: '03 Jun 2026',
    tags: ['Beach Pro Tour', 'Beach Tennis', 'behind-the-scenes', 'Italia'],
  },
];
