import type { Athlete } from '@/types/athlete';

// Dati atleti mock (placeholder). Nessun fetch reale: da sostituire con
// query Supabase. Nomi e numeri realistici ma fittizi. Le foto ciclano sui
// file disponibili in /public/athletes/1.png .. /6.png.
export const mockAthletes: Athlete[] = [
  {
    id: 'paolo-nicolai',
    name: 'Paolo Nicolai',
    nation: 'Italia',
    nationFlag: 'IT',
    photo: '/athletes/1.png',
    circuit: 'FIPAV',
    sport: 'Beach Volley',
    bio: 'Argento olimpico e bandiera del beach volley italiano, gioca un beach volley fatto di muro e potenza.',
    stats: {
      matchesPlayed: 42,
      wins: 31,
      losses: 11,
      winRate: 74,
      seasonPoints: 4200,
      ranking: 6,
      circuit: 'FIPAV',
      nation: 'Italia',
    },
    upcomingEvents: [
      { id: 'e1', title: 'FIPAV Campionato Italiano — Semifinale', circuit: 'FIPAV', date: '28 Jun 2026', location: 'Roma' },
      { id: 'e2', title: 'AIBVC Tour — Tappa di Caorle', circuit: 'AIBVC', date: '05 Jul 2026', location: 'Caorle' },
      { id: 'e3', title: 'King & Queen — Main Draw', circuit: 'King & Queen', date: '12 Jul 2026', location: 'Cervia' },
    ],
    recentMatches: [
      { id: 'm1', title: 'vs Ranghieri / Carambula', result: 'W', date: '20 Jun 2026' },
      { id: 'm2', title: 'vs Rossi / Cottafava', result: 'W', date: '15 Jun 2026' },
      { id: 'm3', title: 'vs Mol / Sørum', result: 'L', date: '08 Jun 2026' },
    ],
  },
  {
    id: 'adrian-carambula',
    name: 'Adrian Carambula',
    nation: 'Italia',
    nationFlag: 'IT',
    photo: '/athletes/2.png',
    circuit: 'AIBVC',
    sport: 'Beach Volley',
    bio: 'Inventore dello "skyball", unisce fantasia e tecnica con un servizio che ha cambiato il gioco.',
    stats: {
      matchesPlayed: 38,
      wins: 25,
      losses: 13,
      winRate: 66,
      seasonPoints: 3650,
      ranking: 11,
      circuit: 'AIBVC',
      nation: 'Italia',
    },
    upcomingEvents: [
      { id: 'e1', title: 'AIBVC Tour — Quarti di finale', circuit: 'AIBVC', date: '29 Jun 2026', location: 'Bibione' },
      { id: 'e2', title: 'FIPAV Campionato Italiano — Tappa', circuit: 'FIPAV', date: '06 Jul 2026', location: 'Lignano' },
      { id: 'e3', title: 'Marathon Tour — Main Draw', circuit: 'Marathon', date: '14 Jul 2026', location: 'Jesolo' },
    ],
    recentMatches: [
      { id: 'm1', title: 'vs Gori / Cattaneo', result: 'W', date: '19 Jun 2026' },
      { id: 'm2', title: 'vs Nicolai / Cottafava', result: 'L', date: '12 Jun 2026' },
      { id: 'm3', title: 'vs Åhman / Hellvig', result: 'W', date: '04 Jun 2026' },
    ],
  },
  {
    id: 'taylor-crabb',
    name: 'Taylor Crabb',
    nation: 'USA',
    nationFlag: 'USA',
    photo: '/athletes/3.png',
    circuit: 'AVP',
    sport: 'Beach Volley',
    bio: 'Difensore tra i migliori al mondo, anima del circuito AVP con riflessi e lettura di gioco fuori categoria.',
    stats: {
      matchesPlayed: 45,
      wins: 33,
      losses: 12,
      winRate: 73,
      seasonPoints: 4500,
      ranking: 4,
      circuit: 'AVP',
      nation: 'USA',
    },
    upcomingEvents: [
      { id: 'e1', title: 'AVP America — Finale', circuit: 'AVP', date: '30 Jun 2026', location: 'Hermosa Beach' },
      { id: 'e2', title: 'Beach Pro Tour — Elite16', circuit: 'BPT', date: '08 Jul 2026', location: 'Gstaad' },
      { id: 'e3', title: 'AVP America — Tappa', circuit: 'AVP', date: '15 Jul 2026', location: 'Chicago' },
    ],
    recentMatches: [
      { id: 'm1', title: 'vs Partain / Benesh', result: 'W', date: '21 Jun 2026' },
      { id: 'm2', title: 'vs Evans / Budinger', result: 'W', date: '14 Jun 2026' },
      { id: 'm3', title: 'vs Gibb / Crabb', result: 'L', date: '07 Jun 2026' },
    ],
  },
  {
    id: 'anders-mol',
    name: 'Anders Mol',
    nation: 'Norvegia',
    nationFlag: 'NO',
    photo: '/athletes/4.png',
    circuit: 'BPT',
    sport: 'Beach Volley',
    bio: 'Campione olimpico e dominatore del Beach Pro Tour, "The Hammer" è il muro più temuto del circuito.',
    stats: {
      matchesPlayed: 48,
      wins: 41,
      losses: 7,
      winRate: 85,
      seasonPoints: 5600,
      ranking: 1,
      circuit: 'BPT',
      nation: 'Norvegia',
    },
    upcomingEvents: [
      { id: 'e1', title: 'Beach Pro Tour — Finale', circuit: 'BPT', date: '27 Jun 2026', location: 'Gstaad' },
      { id: 'e2', title: 'CEV European Championship', circuit: 'CEV', date: '07 Jul 2026', location: 'Vienna' },
      { id: 'e3', title: 'Beach Pro Tour — Elite16', circuit: 'BPT', date: '16 Jul 2026', location: 'Hamburg' },
    ],
    recentMatches: [
      { id: 'm1', title: 'vs Plavins / Tocs', result: 'W', date: '20 Jun 2026' },
      { id: 'm2', title: 'vs Cherif / Ahmed', result: 'W', date: '13 Jun 2026' },
      { id: 'm3', title: 'vs Brouwer / Meeuwsen', result: 'W', date: '06 Jun 2026' },
    ],
  },
  {
    id: 'michele-cappelletti',
    name: 'Michele Cappelletti',
    nation: 'Italia',
    nationFlag: 'IT',
    photo: '/athletes/5.png',
    circuit: 'Beach Pro Tour',
    sport: 'Beach Tennis',
    bio: 'Tra i migliori interpreti italiani del beach tennis, gioco aggressivo a rete e gran senso tattico.',
    stats: {
      matchesPlayed: 36,
      wins: 27,
      losses: 9,
      winRate: 75,
      seasonPoints: 3900,
      ranking: 3,
      circuit: 'Beach Pro Tour',
      nation: 'Italia',
    },
    upcomingEvents: [
      { id: 'e1', title: 'Beach Tennis World Tour — Finale', circuit: 'Beach Pro Tour', date: '29 Jun 2026', location: 'Cervia' },
      { id: 'e2', title: 'ITF Beach Tennis — Tappa', circuit: 'Beach Pro Tour', date: '06 Jul 2026', location: 'Terracina' },
      { id: 'e3', title: 'Campionato Italiano Beach Tennis', circuit: 'FIPAV', date: '13 Jul 2026', location: 'Lignano' },
    ],
    recentMatches: [
      { id: 'm1', title: 'vs Benede / Ramos', result: 'W', date: '19 Jun 2026' },
      { id: 'm2', title: 'vs Gianotti / Cappelletti', result: 'W', date: '12 Jun 2026' },
      { id: 'm3', title: 'vs Hayashi / Oygur', result: 'L', date: '05 Jun 2026' },
    ],
  },
  {
    id: 'antomi-ramos',
    name: 'Antomi Ramos',
    nation: 'Brasile',
    nationFlag: 'BR',
    photo: '/athletes/6.png',
    circuit: 'Beach Pro Tour',
    sport: 'Beach Tennis',
    bio: 'Talento brasiliano del beach tennis, potenza e ritmo nello scambio lo rendono imprevedibile.',
    stats: {
      matchesPlayed: 40,
      wins: 28,
      losses: 12,
      winRate: 70,
      seasonPoints: 4100,
      ranking: 2,
      circuit: 'Beach Pro Tour',
      nation: 'Brasile',
    },
    upcomingEvents: [
      { id: 'e1', title: 'Beach Tennis World Tour — Semifinale', circuit: 'Beach Pro Tour', date: '28 Jun 2026', location: 'Rio de Janeiro' },
      { id: 'e2', title: 'ITF Beach Tennis — Finale', circuit: 'Beach Pro Tour', date: '05 Jul 2026', location: 'Aruba' },
      { id: 'e3', title: 'Beach Tennis World Tour — Tappa', circuit: 'Beach Pro Tour', date: '12 Jul 2026', location: 'Cervia' },
    ],
    recentMatches: [
      { id: 'm1', title: 'vs Cappelletti / Gianotti', result: 'L', date: '20 Jun 2026' },
      { id: 'm2', title: 'vs Hayashi / Oygur', result: 'W', date: '13 Jun 2026' },
      { id: 'm3', title: 'vs Maier / Krumich', result: 'W', date: '06 Jun 2026' },
    ],
  },
  {
    id: 'agustin-tapia',
    name: 'Agustín Tapia',
    nation: 'Argentina',
    nationFlag: 'AR',
    photo: '/athletes/1.png',
    circuit: 'Premier Padel',
    sport: 'Padel',
    bio: '"El Mozart de Catamarca": estro, anticipo e mani educate. Tra i numeri uno del padel mondiale.',
    stats: {
      matchesPlayed: 50,
      wins: 39,
      losses: 11,
      winRate: 78,
      seasonPoints: 5200,
      ranking: 1,
      circuit: 'Premier Padel',
      nation: 'Argentina',
    },
    upcomingEvents: [
      { id: 'e1', title: 'Premier Padel — Finale', circuit: 'Premier Padel', date: '27 Jun 2026', location: 'Madrid' },
      { id: 'e2', title: 'Premier Padel — Major', circuit: 'Premier Padel', date: '07 Jul 2026', location: 'Roma' },
      { id: 'e3', title: 'Premier Padel — P1', circuit: 'Premier Padel', date: '15 Jul 2026', location: 'Parigi' },
    ],
    recentMatches: [
      { id: 'm1', title: 'vs Galán / Chingotto', result: 'W', date: '21 Jun 2026' },
      { id: 'm2', title: 'vs Coello / Tapia', result: 'W', date: '14 Jun 2026' },
      { id: 'm3', title: 'vs Lebrón / Stupaczuk', result: 'L', date: '07 Jun 2026' },
    ],
  },
  {
    id: 'alejandro-galan',
    name: 'Alejandro Galán',
    nation: 'Spagna',
    nationFlag: 'ES',
    photo: '/athletes/2.png',
    circuit: 'Premier Padel',
    sport: 'Padel',
    bio: 'Potenza pura e dritto devastante: lo spagnolo è una delle colonne del circuito Premier Padel.',
    stats: {
      matchesPlayed: 49,
      wins: 36,
      losses: 13,
      winRate: 73,
      seasonPoints: 4900,
      ranking: 3,
      circuit: 'Premier Padel',
      nation: 'Spagna',
    },
    upcomingEvents: [
      { id: 'e1', title: 'Premier Padel — Semifinale', circuit: 'Premier Padel', date: '28 Jun 2026', location: 'Madrid' },
      { id: 'e2', title: 'Premier Padel — Major', circuit: 'Premier Padel', date: '06 Jul 2026', location: 'Roma' },
      { id: 'e3', title: 'Premier Padel — P2', circuit: 'Premier Padel', date: '14 Jul 2026', location: 'Malmö' },
    ],
    recentMatches: [
      { id: 'm1', title: 'vs Tapia / Coello', result: 'L', date: '21 Jun 2026' },
      { id: 'm2', title: 'vs Lebrón / Stupaczuk', result: 'W', date: '13 Jun 2026' },
      { id: 'm3', title: 'vs Navarro / Di Nenno', result: 'W', date: '05 Jun 2026' },
    ],
  },
];

export function getAthleteById(id: string): Athlete | undefined {
  return mockAthletes.find((a) => a.id === id);
}
